<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CommoditiesSeeder extends Seeder
{
    public function run()
    {
        DB::table('commodities')->insert([
            [
                'title' => 'Навес арочный 5.5 x 7 м',
                'description' => 'Прочный арочный навес с покрытием из поликарбоната. Отличное решение для автомобиля или зоны отдыха.',
                'price' => 350000.00,
                'size' => '5.5 x 7 м',
                'material' => 'Поликарбонат',
                'type' => 'Усиленный',
                'image' => 'images/commodities/1.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Навес односкатный 3 x 6 м',
                'description' => 'Компактный и надежный навес, идеален для дачи или частного двора.',
                'price' => 210000.00,
                'size' => '3 x 6 м',
                'material' => 'Профнастил',
                'type' => 'Стандарт',
                'image' => 'images/commodities/2.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Навес с хозблоком 6 x 6 м',
                'description' => 'Функциональный навес с встроенным хозблоком. Подходит для хранения инструмента и техники.',
                'price' => 480000.00,
                'size' => '6 x 6 м',
                'material' => 'Металлочерепица',
                'type' => 'Премиум',
                'image' => 'images/commodities/3.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Полуарочный навес 6 x 9 м',
                'description' => 'Элегантный полуарочный навес для стоянки 2 автомобилей или организации зоны отдыха.',
                'price' => 420000.00,
                'size' => '6 x 9 м',
                'material' => 'Поликарбонат',
                'type' => 'Усиленный',
                'image' => 'images/commodities/4.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Двухскатный навес 7 x 10 м',
                'description' => 'Надежная двухскатная конструкция для покрытия больших площадей. Отлично подходит для производственных объектов.',
                'price' => 670000.00,
                'size' => '7 x 10 м',
                'material' => 'Профнастил',
                'type' => 'Промышленный',
                'image' => 'images/commodities/5.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Козырек из поликарбоната 2 x 1.2 м',
                'description' => 'Простой и удобный козырек над входной дверью. Подходит для частных и коммерческих объектов.',
                'price' => 45000.00,
                'size' => '2 x 1.2 м',
                'material' => 'Поликарбонат',
                'type' => 'Стандарт',
                'image' => 'images/commodities/6.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Садовый навес 3 x 4 м',
                'description' => 'Легкий навес для установки в саду, защита от солнца и дождя. Устанавливается без фундамента.',
                'price' => 160000.00,
                'size' => '3 x 4 м',
                'material' => 'Профнастил',
                'type' => 'Легкий',
                'image' => 'images/commodities/7.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Навес для мангала 2.5 x 3 м',
                'description' => 'Специальный навес для защиты зоны барбекю. Подходит для дачи и зоны отдыха.',
                'price' => 110000.00,
                'size' => '2.5 x 3 м',
                'material' => 'Металл',
                'type' => 'Жаростойкий',
                'image' => 'images/commodities/8.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Навес с хозблоком 5 x 6 м',
                'description' => 'Универсальный навес с встроенным хозблоком — идеальное решение для хранения инвентаря и техники.',
                'price' => 520000.00,
                'size' => '5 x 6 м',
                'material' => 'Профнастил + металл',
                'type' => 'Комбинированный',
                'image' => 'images/commodities/9.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Навес для дачи 4 x 6 м',
                'description' => 'Эстетичный и функциональный навес для отдыха на даче. Легкий монтаж, привлекательный вид.',
                'price' => 275000.00,
                'size' => '4 x 6 м',
                'material' => 'Поликарбонат',
                'type' => 'Летний',
                'image' => 'images/commodities/10.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Навес для бассейна 3.5 x 6 м',
                'description' => 'Прочный навес для бассейнов. Обеспечивает защиту от мусора, пыли и осадков.',
                'price' => 390000.00,
                'size' => '3.5 x 6 м',
                'material' => 'Поликарбонат',
                'type' => 'Раздвижной',
                'image' => 'images/commodities/11.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Кованый козырек 2 x 1 м',
                'description' => 'Элегантный кованый козырек, подчеркивающий стиль и статус здания. Индивидуальный рисунок.',
                'price' => 75000.00,
                'size' => '2 x 1 м',
                'material' => 'Металл',
                'type' => 'Кованный',
                'image' => 'images/commodities/12.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Навес из металлочерепицы 5 x 7 м',
                'description' => 'Стильный навес из металлочерепицы. Идеален для частного дома и зоны парковки.',
                'price' => 410000.00,
                'size' => '5 x 7 м',
                'material' => 'Металлочерепица',
                'type' => 'Стандарт',
                'image' => 'images/commodities/13.png',
                'created_at' => now(),
                'updated_at' => now(),
            ],


        ]);
    }
}